In [1]:
#Call Libraries
import numpy as np
import pandas as pd

In [31]:
#Load data from .csv file to dataframe

df=pd.read_csv("D:/Dummydata/Biometric_Data.csv")

In [32]:
df

,Date,Employee Code,Employee Name,Company,Department,Category,Degination,Grade,Team,Shift,In Time,Out Time,Duration
0,9/20/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,NaN,NaN,0:00
1,9/21/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,NaN,NaN,0:00
2,9/22/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,NaN,NaN,0:00
3,9/23/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,13:09,19:07,5:58
4,9/24/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,12:41,17:32,4:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.columns

# To see the columns available

Index(['Date', ' Employee Code ', 'Employee Name', 'Company ', 'Department',
       'Category ', 'Degination', 'Grade', 'Team', 'Shift', ' In Time ',
       'Out Time ', ' Duration '],
      dtype='object')

In [34]:
for i in df['Employee Name']:
    print(i)

John
John
John
John
John
Merry Math
Merry Math
Merry Math
Merry Math
Merry Math
Stela Kevin
Stela Kevin
Stela Kevin
Stela Kevin
Stela Kevin
Peter Molsberg
Peter Molsberg
Peter Molsberg
Peter Molsberg
Peter Molsberg
Merry Charlton
Merry Charlton
Merry Charlton
Merry Charlton
Merry Charlton
Kemlin Green
Kemlin Green
Kemlin Green
Kemlin Green
Kemlin Green
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [35]:
for i in df['Out Time '] :
    
    print(i)
    
 #Iteration through for loop to print a column data

nan
nan
nan
19:07
17:32
nan
nan
19:25
19:14
19:15
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
18:26
nan
nan
19:26
19:09
19:04
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [38]:
selected_rows = dataframe[~dataframe['Out Time ']. isna()]

# ~  is a not operation,it staands for negation. This will print all outtime of employees not having outtime as NaN

In [39]:
selected_rows

,Date,Employee Code,Employee Name,Company,Department,Category,Degination,Grade,Team,Shift,In Time,Out Time,Duration
3,9/23/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,13:09,19:07,5:58
4,9/24/2021,1.0,John,ABC Incorporation,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,12:41,17:32,4:50
7,9/22/2021,2.0,Merry Math,ABC Incorporation,Contract,Default,Manager,NaN,NaN,GS,8:53,19:25,10:22
8,9/23/2021,2.0,Merry Math,ABC Incorporation,Contract,Default,Manager,NaN,NaN,GS,10:04,19:14,9:10
9,9/24/2021,2.0,Merry Math,ABC Incorporation,Contract,Default,Manager,NaN,NaN,GS,9:50,19:15,9:20
24,9/24/2021,5.0,Merry Charlton,ABC Incorporation,DBDR,Default,Manager,NaN,Derek Stegelmeier,GS,8:18,18:26,9:27
27,9/22/2021,6.0,Kemlin Green,ABC Incorporation,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:27,19:26,9:59
28,9/23/2021,6.0,Kemlin Green,ABC Incorporation,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:31,19:09,9:38
29,9/24/2021,6.0,Kemlin Green,ABC Incorporation,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:03,19:04,10:01

In [24]:
selected_rows

,Date,Employee Code,Employee Name,Company,Department,Category,Degination,Grade,Team,Shift,In Time,Out Time,Duration
3,9/23/2021,1,Bhaskar Datta,Legal O2,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,13:09,19:07,5:58
4,9/24/2021,1,Bhaskar Datta,Legal O2,Admin,Default,Senior Business Manager,NaN,Harry Buck,GS,12:41,17:32,4:50
7,9/22/2021,2,Namrata Dutta,Legal O2,Contract,Default,Manager,NaN,NaN,GS,8:53,19:25,10:22
8,9/23/2021,2,Namrata Dutta,Legal O2,Contract,Default,Manager,NaN,NaN,GS,10:04,19:14,9:10
9,9/24/2021,2,Namrata Dutta,Legal O2,Contract,Default,Manager,NaN,NaN,GS,9:50,19:15,9:20
24,9/24/2021,5,Navonil Bhattacharya,Legal O2,DBDR,Default,Manager,NaN,Derek Stegelmeier,GS,8:18,18:26,9:27
27,9/22/2021,6,Deborpita Nandi,Legal O2,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:27,19:26,9:59
28,9/23/2021,6,Deborpita Nandi,Legal O2,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:31,19:09,9:38
29,9/24/2021,6,Deborpita Nandi,Legal O2,HR,Default,HR & Admin,NaN,Manidipa Aich,GS,9:03,19:04,10:01
48,9/23/2021,10,Tanmoy Sukul,Legal O2,DB,Default,Manager,NaN,Derek Stegelmeier,GS,9:13,19:23,10:10
53,9/23/2021,11,Dipankar Majumdar,Legal O2,DB,Default,Team Leader,NaN,Tanmoy Sukul,GS,8:04,15:18,6:19
67,9/22/2021,14,Debojit Roy,Legal O2,Contract,Default,Senior Associate,NaN,Namrata Dutta,GS,8:16,19:25,10:22
73,9/23/2021,15,Kaninika Ghosh,Legal O2,DB,Default,Team Leader,NaN,Tanmoy Sukul,GS,8:47,18:24,9:21
77,9/22/2021,16,Debadipta Bhattacharya,Legal O2,DB,Default,Team Leader,NaN,Tanmoy Sukul,GS,9:47,19:26,9:35
78,9/23/2021,16,Debadipta Bhattacharya,Legal O2,DB,Default,Team Leader,NaN,Tanmoy Sukul,GS,9:22,19:13,9:46
79,9/24/2021,16,Debadipta Bhattacharya,Legal O2,DB,Default,Team Leader,NaN,Tanmoy Sukul,GS,9:37,19:15,9:33
88,9/23/2021,18,Malay Sarkar,Legal O2,DB,Default,Senior Associate,NaN,Tanmoy Sukul,GS,7:02,17:42,8:43
92,9/22/2021,19,Vikash Kumar Jha,Legal O2,Contract,Default,Senior Associate,NaN,Namrata Dutta,GS,9:02,19:14,10:12
106,9/21/2021,22,Saurab Dutta,Legal O2,DB,Default,IT Manager,NaN,Tanmoy Sukul,GS,9:14,19:30,10:16
107,9/22/2021,22,Saurab Dutta,Legal O2,DB,Default,IT Manager,NaN,Tanmoy Sukul,GS,9:04,19:59,10:55
108,9/23/2021,22,Saurab Dutta,Legal O2,DB,Default,IT Manager,NaN,Tanmoy Sukul,GS,8:54,20:02,10:58
109,9/24/2021,22,Saurab Dutta,Legal O2,DB,Default,IT Manager,NaN,Tanmoy Sukul,GS,8:58,19:16,10:17
123,9/23/2021,25,Anirban Sen,Legal O2,DB,Default,Associate,NaN,Tanmoy Sukul,GS,7:37,17:57,8:53
162,9/22/2021,33,Poulami Bera,Legal O2,DR,Default,Associate,NaN,Navonil Bhattacharya,GS,9:02,19:08,10:06
182,9/22/2021,37,Manidipa Aich,Legal O2,HR,Default,HR Manager,NaN,Harry Buck,GS,11:16,19:47,8:31
183,9/23/2021,37,Manidipa Aich,Legal O2,HR,Default,HR Manager,NaN,Harry Buck,GS,9:37,19:10,9:33
184,9/24/2021,37,Manidipa Aich,Legal O2,HR,Default,HR Manager,NaN,Harry Buck,GS,9:10,19:17,10:07
193,9/23/2021,39,Soumen Roy,Legal O2,DB,Default,Senior Data Analyst,NaN,Tanmoy Sukul,GS,8:53,19:19,10:20
198,9/23/2021,40,Deblina Chakrabarty,Legal O2,Admin,Default,Personal Assistant to CEO,NaN,Harry Buck,GS,9:51,19:13,9:22
199,9/24/2021,40,Deblina Chakrabarty,Legal O2,Admin,Default,Personal Assistant to CEO,NaN,Harry Buck,GS,10:21,19:16,8:55
202,9/22/2021,41,Jaiwardhan Samdarshi,Legal O2,Contract,Default,Senior Associate,NaN,Namrata Dutta,GS,8:57,19:09,10:10
207,9/22/2021,42,Wizdan Parwez,Legal O2,DB,Default,Associate,NaN,Tanmoy Sukul,GS,8:43,18:48,9:49
208,9/23/2021,42,Wizdan Parwez,Legal O2,DB,Default,Associate,NaN,Tanmoy Sukul,GS,8:14,19:07,10:08
209,9/24/2021,42,Wizdan Parwez,Legal O2,DB,Default,Associate,NaN,Tanmoy Sukul,GS,8:30,18:47,9:48
232,9/22/2021,47,Aniruddha Sarkar,Legal O2,Contract,Default,Senior Associate,NaN,Namrata Dutta,GS,9:02,19:10,10:08
237,9/22/2021,48,Sourav Mohan Chatterjee,Legal O2,Contract,Default,Senior Associate,NaN,Namrata Dutta,GS,9:02,19:29,10:27
255,9/20/2021,LG201,LG201,Default,Default,Default,NaN,NaN,NaN,GS,13:59,18:33,4:34
256,9/21/2021,LG201,LG201,Default,Default,Default,NaN,NaN,NaN,GS,14:13,19:35,5:22
257,9/22/2021,LG201,LG201,Default,Default,Default,NaN,NaN,NaN,GS,11:14,20:00,8:46
258,9/23/2021,LG201,LG201,Default,Default,Default,NaN,NaN,NaN,GS,9:16,20:02,10:46
259,9/24/2021,LG201,LG201,Default,Default,Default,NaN,NaN,NaN,GS,11:36,19:17,7:41
261,9/21/2021,LG20118,Md Mohiuddin Siddique,Legal O2,IT,Default,System Administrator,NaN,Saurab Dutta,GS,13:37,19:30,5:53
262,9/22/2021,LG20118,Md Mohiuddin Siddique,Legal O2,IT,Default,System Administrator,NaN,Saurab Dutta,GS,11:08,19:55,8:47
263,9/23/2021,LG20118,Md Mohiuddin Siddique,Legal O2,IT,Default,System Administrator,NaN,Saurab Dutta,GS,9:10,19:57,10:47
264,9/24/2021,LG20118,Md Mohiuddin Siddique,Legal O2,IT,Default,System Administrator,NaN,Saurab Dutta,GS,9:26,19:12,9:46
265,9/20/2021,LGO20,LGO20,Default,Default,Default,NaN,NaN,NaN,GS,9:34,13:24,3:50
267,9/22/2021,LGO20,LGO20,Default,Default,Default,NaN,NaN,NaN,GS,9:10,11:18,2:08
268,9/23/2021,LGO20,LGO20,Default,Default,Default,NaN,NaN,NaN,GS,9:01,19:11,10:10
277,9/22/2021,LGO20094,Ankita Roy,Legal O2,Contract,Default,Senior Associate,Default,Namrata Dutta,GS,9:02,19:29,10:27
288,9/23/2021,LGO20124,Alok Kumar Mishra,Legal O2,Finance,Default,Manger of Finance & Reporting,Default,Harry Buck,GS,8:55,19:07,10:08
289,9/24/2021,LGO20124,Alok Kumar Mishra,Legal O2,Finance,Default,Manger of Finance & Reporting,Default,Harry Buck,GS,9:24,18:37,9:13

In [15]:
selected_rows.to_excel("D:\Biometric_play.xlsx")